# these are automatically called if no cache
# @name author

### use export variable
GET https://httpbin.org/json
@author={{response.parsedBody.slideshow.author}}

### use global variable
# these are not automatically called if no cache
GET https://httpbin.org/json

{{
  $global.mydata = response.parsedBody.slideshow.author
}}
