# register, login and test generated token tests

### register
POST /identity/register
Content-Type: application/json
{
  "username": "{{email}}",
  "password": "{{password}}",
  "email": "{{email}}"
}


### login and get token
# @name auth
POST /identity/login
Content-Type: application/json
{
  "username": "{{email}}",
  "email": "{{email}}",
  "password": "{{password}}"
}
@auth={{response.parsedBody}}

### test cookie auth
# @ref auth
GET /auth/hello
# Authorization: Bearer {{ auth.accessToken }}

### test token auth
# @no-cookie-jar
# @ref auth
GET /auth/hello
Authorization: Bearer {{ auth.accessToken }}

###
# @name gen
# @ref auth
GET /auth/testtoken
Authorization: Bearer {{auth.accessToken}}

@gen={{response.parsedBody}}

### 
# @ref gen
GET /auth/hello
Authorization: Bearer {{gen.accessToken}}

