# register, login and test generated token tests

### register
POST /identity/register
Content-Type: application/json
{
  "username": "{{email}}",
  "password": "{{password}}",
  "email": "{{email}}"
}


### login and get token
# @name auth
POST /identity/unauthlogin
Content-Type: application/json
{
  "username": "{{email}}",
  "email": "{{email}}",
  "password": "{{password}}"
}
@auth={{response.parsedBody}}

### test cookie auth
# @ref auth
GET /auth/hello
# Authorization: Bearer {{ auth.access_token }}

### test token auth
# @no-cookie-jar
# @ref auth
GET /auth/hello
Authorization: Bearer {{ auth.access_token }}


### test token only endpoint with token
# @no-cookie-jar
# @ref auth
GET /tokenonly
Authorization: Bearer {{ auth.access_token }}

### test token only endpoint with cookie
# @ref auth
GET /tokenonly

### test token only endpoint with cookie
# @ref auth
GET /cookieonly

### test token only endpoint with token
# @no-cookie-jar
# @ref auth
GET /cookieonly
Authorization: Bearer {{ auth.access_token }}




### test token only endpoint with token
# @no-cookie-jar
# @ref auth
GET /auth/tokenonly
Authorization: Bearer {{ auth.access_token }}

### test token only endpoint with cookie
# @ref auth
GET /auth/tokenonly

### test token only endpoint with cookie
# @ref auth
GET /auth/cookieonly

### test token only endpoint with token
# @no-cookie-jar
# @ref auth
GET /auth/cookieonly
Authorization: Bearer {{ auth.access_token }}

